
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 25 13:02:56 VET 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MQ = 19;
  public static final int MIGUAL = 21;
  public static final int POR = 13;
  public static final int MIRARARRIBA = 38;
  public static final int MIRARDER = 40;
  public static final int INT = 28;
  public static final int FOR = 27;
  public static final int RCOR = 33;
  public static final int AVANZAR = 36;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int IGUAL = 12;
  public static final int RPAR = 17;
  public static final int OR = 25;
  public static final int BOOL = 29;
  public static final int ASIGNA = 9;
  public static final int NUM = 3;
  public static final int IF = 5;
  public static final int ID = 4;
  public static final int EOF = 0;
  public static final int TRUE = 34;
  public static final int error = 1;
  public static final int DIF = 23;
  public static final int mIGUAL = 22;
  public static final int MENOS = 14;
  public static final int mQ = 20;
  public static final int MOD = 11;
  public static final int PCOMA = 18;
  public static final int LBRACK = 30;
  public static final int MIRARIZQ = 39;
  public static final int ELSE = 6;
  public static final int RBRACK = 31;
  public static final int WHILE = 8;
  public static final int MIRARABAJO = 37;
  public static final int LCOR = 32;
  public static final int PROG = 2;
  public static final int LPAR = 16;
  public static final int FALSE = 35;
  public static final int ENTRE = 15;
  public static final int DO = 7;
  public static final int MAS = 10;
}

